### ISSUE TITLE
Selecting a different chromosome without reloading the whole page

### ISSUE THREAD

**Issue by mnori** [wtsi-web/Genoverse#23]
I'm currently integrating Genoverse into a genomic data site. So far I'm really liking it. 

I made a chromosome <select> menu, which I want to use to change the visible chromosome dynamically, i.e. without reloading the whole page. I did try hacking around with Genoverse.init() and a few other methods, to try and force it to initialise with an altered "chr" parameter in the config, but just ended up with javascript errors.

Adding a method to easily change the chromosome would be nice. Or just point me in the right direction. :)

Thank you,
Matt

**Comment by simonbrent** [comment]
I've tried to make a function to do this a couple of times, but ran out of time and patience before getting something that worked bug-free every time. The major problem is that Genoverse is just not set up to deal with a chromosome change, so there are no solutions which don't require either hackery or major rewrites!

I think you want to be doing is setting the chr, then calling Genoverse.reset() rather than using Genoverse.init(). This is still not a perfect solution though, since track models won't be re-initialized if the track has url = false (this is the case with Scalebar, at the very least). Additionally, I haven't really tested the reset functionality for a long time - it was written to deal with dynamically changing the width of Genoverse, and the project I work on now doesn't ever need to do that, so I don't even know if it still works as expected.

Still, if you CAN get it to work, I'd be happy/grateful to take a pull request ;-)

**Comment by AntonPetrov** [comment]
For what it's worth, when I need to switch to a different chromosome (or genome) I just delete the Genoverse object and then immediately recreate it with new settings. This is not ideal, but at least there is no page refresh.

**Comment by mnori** [comment]
@simonbrent Thanks for the advice! I gave reset() a try, but didn't have much luck unfortunately. If I can find a solution, I'll submit a pull request.

@AntonPetrov I tried recreating the window.genoverse object but got errors - I think there must have been some other residual variables lurking in the DOM somewhere.

**Comment by fossilfriend** [comment]
This is a beautiful genome browser and I'd love to use it in my project except I'd agree that not only being able to go to a specific chromosome, but a specific location (e.g, by feature name such as a gene or by coordinates) is a real limiting factor.

**Comment by simonbrent** [comment]
@fossilfriend Going to a specific location is possible (see https://decipher.sanger.ac.uk/browser) but this requires code outside of the current scope of Genoverse.

Specifically, this page is taking the contents of the input box and turning it into a location in the form chr:start-end when the Go button is clicked. A new browser is then created, focused on that location.

This is easy for the case where coordinates are entered into the input box, and is also possible for chromosome bands, which can be converted into coordinates using the genome object, but for feature names you require a back-end that knows what and where these features are.

A while ago I wrote a plugin that would allow you to jump to the location of a gene, given the gene name, but it could only work when the gene in question has already been loaded into Genoverse, and therefore wasn't useful most of the time. Since Genoverse is entirely front-end, it is not feasible to include this code in the repo.

**Comment by simonbrent** [comment]
You can now use `genoverse.moveTo(chr, start, end)` to change chromosomes.
