### ISSUE TITLE
Tracks for Coverage 

### ISSUE THREAD

**Issue by oracleruiz** [wtsi-web/Genoverse#31]
Hi, 

We are using Genoverse for a very important project and part of the requirements is to display a track for **Coverage**. But I don't see a clue how to implement this. Does Genoverse have a way to display this type of track? Is it supported?

**Comment by simonbrent** [comment]
Can you please explain what you mean by coverage?

**Comment by alex7olaru** [comment]
Hi Simon,

Thank you for the quick for the reply. We would need to create a coverage track similar to this one:

http://www.broadinstitute.org/igv/AlignmentData#coverage

This is a high-profile project with a research institute. So far we have been able to integrate Genoverse for a number of functions: gene model and variants tracks, control the browser programatically (i.e. from other UI elements outside of the Genoverse browser widget): move at different positions within a chromosome, across chromosomes, add new tracks, etc. We also like Genoverse's json support.

The coverage track though is a very important factor in enabling us to continue to use Genoverse in this project. Any advice you could provide on how to create such a track would be appreciated. At this point the only option we see is having to create the track completely from the ground-up and that would be too time consuming for this project.

**Comment by simonbrent** [comment]
Ok, here's an example track that will serve your purposes:

```
Genoverse.Track.extend({
  name       : 'Coverage',
  color      : '#999',
  30000      : false,
  autoHeight : true,

  data: [ // example data
    { start: 32321921, end: 32321921, height: 10 },
    { start: 32321922, end: 32321922, height: 15 },
    { start: 32321923, end: 32321923, height: 40, colors: [[ 0.2, '#73E973' ], [ 0.8, '#DE4C61' ]], decorations: true }
  ],

  afterAddDomElements: function () {
    this.imgContainer.addClass('gv-flip');
  },

  decorateFeature: function (feature, context, scale) {
    var position = feature.position[scale];
    var x        = position.X;
    var y        = position.Y;
    var w        = position.width;
    var colors   = feature.colors;
    var h;

    for (var i = 0; i < colors.length; i++) {
      h = colors[i][0] * feature.height;

      context.fillStyle = colors[i][1];
      context.fillRect(x, y, w, h);

      y += h;
    }
  }
})
```

Here's what is going on:

The default feature color is set to #999.
The height of each feature is specified in it's hash in the track's data attribute (you will not be using this attribute, you'll be loading the data by AJAX instead, but the format should be the same).
The last feature has a colors array, specifying the percentage height of the color, and the color itself. The decorateFeature function then turns this array into colors on the bar, providing the feature has the decorations property set to true.
The afterAddDomElements function adds a class to flip the image so that features appear to start at the bottom of the image, rather than the top.

You will also need a populateMenu function to display a popup based on other metadata you have for each position. Given that you will be supplying this metadata in your AJAX request, you may choose to use that in decorateFeature, rather than calculating a colors array on your back-end.

Hope this helps.

Simon

**Comment by alex7olaru** [comment]
Thanks much Simon. This will work well the generation of the histogram which depicts the relative weighting of each nucleotide variant across all reads at a particular position + the number of total reads. The coverage track in IGV includes though also a display of each individual strip/read with markers (illustrated either as nucleotide colored symbols/letters or as only colors representing each nucleotide - depending on resolution/scale) for all variants to the reference genome. One could argue that the histogram conveys about the same information as the individual reads but at a more aggregate level. Our users are interested though in seeing the details too.

Any ideas how we could display the individual reads too + variants markers? We could split this into a separate track too, if that would be easier: one track that provides the summary (the histogram) and another track for the details (the individual reads). I understand now how a rectangle could be drawn to span one or multiple positions but I don't know how to draw them stacked on top of each other to illustrate each separate read. 

Also if there is an example of how to setup a track to be fed with a BAM file instead of JSON, please let us know. We could not find one in the documentation/code. The doc talks about dragging and dropping a bam file into the browser but nothing seems to be happening when we do that. It would be preferable to set one up programatically. Our BAM files come from an Hadoop environment and we might not have the necessary libraries on the backend to read in the BAM files and generate json for the coverage data to send to the client. We might need to have the raw bytes come to the browser and then use a JS parsing library to extract the data into a format that the track can work for the coverage track.

**Comment by simonbrent** [comment]
Ah, I didn't realize that the two parts of the image on http://www.broadinstitute.org/igv/AlignmentData#coverage where linked.

It would indeed be easiest to do this as a separate track in Genoverse, and it's pretty simple - all you have to do to get stacked rectangles is to set the property `bump: true` for the track. However, I think the easiest way to make this track, given your mention of BAM files, would be to use `Genoverse.Track.File.BAM` (https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Track/library/File/BAM.js) setting the track's `url` property to be the url of your .bam file on your server. 

Please be aware that the code to parse BAM files comes from a 3rd party, and I don't fully understand its workings or limitations. However, I have tested out reasonable-sized files and, providing they have asscociated .bai files and the region you're looking at is not too large, it performs quite well.

It should also be noted that `Genoverse.Track.File.BAM` currently uses a sequence view, so each base in the rectangle will be colored based on its letter, with the letters shown when you've zoomed in enough. If you want the rectangles to be grey with colored letters, you will have to use a view that extends `Genoverse.Track.View.Sequence` (https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Track/View/Sequence.js), changing the `colors` and `labelColors` properties. You will also need to provide a `decorateFeature` function to draw triangles on the ends of your reads, if required.
